<div id="tableToExport" ng-hide="louis.statusTableToExport">
			<style>
				#tableToExport .table-header{
					background: #5bd0fb;
				}
			</style>
		<table>
			<tr>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td colspan="3"><h3>Danh sách người đoạt {{louis.adward_obj[louis.adward]['title']}}</h3></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
		</table>
      <table border="1">
        <thead>
          <thead class="table-header">
            <th>ID</th>
            <th>Họ tên</th>
            <th>Mã số</th>
          </thead>
        </thead>
        <tbody>
          <tr ng-repeat="obj in louis.people">
            <td>{{$index + 1}}</td>
            <td>{{obj.name}}</td>
            <td>{{obj.code}}</td>
          </tr>
          </tbody>
      </table>
    </div>