<!DOCTYPE html>
<html lang="vi">
<head>
	<meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8">
	<meta charset="utf-8">	
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>luckynumber | layout.phtml</title>
	<!-- css -->
	<link href="/public/assets/css/bootstrap.min.css" rel="stylesheet">
	<link href="/public/css/style.css" rel="stylesheet">
	<link href="/public/css/font-awesome.css" rel="stylesheet">
	<!-- js -->
		
	<script src="/public/js/angular.js"></script>	
	<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.9/angular-route.min.js"></script>	-->

	<script src="/public/js/animate.js"></script>	
	 <script data-require="ui-bootstrap@*" data-semver="0.12.1" src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.12.1.min.js"></script>
	 <script data-require="jquery@*" data-semver="2.1.4" src="/public/js/jquery.2.14.min.js"></script> 
	<script src="/public/js/angular-file-saver.bundle.min.js"></script>
	<script src="/public/js/app.js"></script>	
	<script src="/public/js/customer_controller.js"></script>	
	<!--<script src="/public/js/customer_controller.js"></script>-->
	<script src="/public/js/bootstrap.min.js"></script>
</head>
<body ng-app="louis">

	<header id="site-header">
	</header><!-- #site-header -->

	<main id="site-content" role="main">
	<?php echo $this->layout()->content; ?>
	</main><!-- #site-content -->

	<footer id="site-footer" role="contentinfo">
	</footer><!-- #site-footer -->

	
</body>
</html>